[project]
name = "myproject-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.2",
    "openai-agents>=0.3.0",
    "python-dotenv>=1.1.1",
]
